image: gitpod/workspace-full
tasks:
  - command: python3 -m http.server 8080
    name: Static Server
  - openMode: split-right
    command: echo SplitTerminal
  - openIn: left
    command: echo LeftPanelTerminal
ports:
  - port: 8000
    onOpen: open-preview